QuoraClone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='base.html')),
    path('main/', include('questions.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/<str:username>/', views.userProfile, name='profile'),
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('change-password/', views.changePassword, name='changePassword'),

]

questions/urls.py
from django.urls import path, include
from . import views

app_name = 'questions'
urlpatterns = [
    path('home/', views.userFeed, name='feed'),
    path('all-users/', views.get_all_users, name='get_all_users'),
    path('home/ques/<str:question_title>/', views.get_question, name='question_card'),
    path('<str:username>/all_questions/', views.get_profile_questions, name='user_questions'),
    path('<str:username>/all_answers/', views.get_profile_answers, name='user_answers'),
]

questions/models.py
from django.db import models
from django.conf import settings


class QuestionVotedUser(models.Model):
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    voting_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    voting_value = models.IntegerField()

    class Meta:
        unique_together = ('question', 'voting_user')


class Question(models.Model):
    question_asker = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question_title = models.CharField(max_length=120)
    question_description = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.question_title[:30]

    @property
    def get_question_upvoters(self):
        qs = self.questionvoteduser_set.filter(voting_value=1)
        upvoters = []
        for upvoter in qs:
            upvoters.append(upvoter.voting_user)
        return upvoters

    @property
    def get_question_downvoters(self):
        qs = self.questionvoteduser_set.filter(voting_value=-1)
        downvoters = []
        for downvoter in qs:
            downvoters.append(downvoter.voting_user)
        return downvoters


class AnswerVotedUser(models.Model):
    answer = models.ForeignKey('Answer', on_delete=models.CASCADE)
    voting_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    voting_value = models.IntegerField()

    class Meta:
        unique_together = ('answer', 'voting_user')


class Answer(models.Model):
    answerer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)
    answer_text = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.answer_text[:30]

    @property
    def get_answer_upvoters(self):
        qs = self.answervoteduser_set.filter(voting_value=1)
        upvoters = []
        for upvoter in qs:
            upvoters.append(upvoter.voting_user)
        return upvoters

    @property
    def get_answer_downvoters(self):
        qs = self.answervoteduser_set.filter(voting_value=-1)
        downvoters = []
        for downvoter in qs:
            downvoters.append(downvoter.voting_user)
        return downvoters

questions/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth import get_user_model
from .models import Question, Answer, QuestionVotedUser, AnswerVotedUser

User = get_user_model()


def get_profile_questions(request, username):
    profile = User.objects.get(username=username)
    profile_questions_list = Question.objects.filter(question_asker=profile)
    context = {
        'questions_list': profile_questions_list
    }
    return render(request, 'questions/profile_questions_list.html', context)


def get_profile_answers(request, username):
    profile = User.objects.get(username=username)
    profile_answers_list = Answer.objects.filter(answerer=profile)
    context = {
        'profile_answers_list': profile_answers_list
    }
    return render(request, 'questions/profile_answers_list.html', context)


def get_question(request, question_title):
    user = request.user
    question = Question.objects.get(question_title=question_title)
    answer = question.answer_set.all()
    queupvote = request.GET.get('queupvote' or None)
    quedownvote = request.GET.get('quedownvote' or None)
    ansupvote = request.GET.get('ansupvote' or None)
    ansdownvote = request.GET.get('ansdownvote' or None)
    fetched_answer = None
    if request.GET.get('ans_number'):
        fetched_answer = answer[int(request.GET.get('ans_number')) - 1]

    if queupvote or quedownvote or ansupvote or ansdownvote:
        if user.is_authenticated:
            try:
                try:
                    ansVotedUser = AnswerVotedUser.objects.get(
                        Q(answer=fetched_answer),
                        Q(voting_user=user),
                        Q(voting_value=1) | Q(voting_value=-1))

                except:
                    if request.GET['ansupvote']:
                        AnswerVotedUser.objects.create(answer=fetched_answer, voting_user=user, voting_value=1)
                        messages.add_message(request, messages.SUCCESS, 'You upvoted this answer.')
                    elif request.GET['ansdownvote']:
                        AnswerVotedUser.objects.create(question=question, voting_user=user, voting_value=-1)
                        messages.add_message(request, messages.SUCCESS, 'You downvoted this answer.')
                else:
                    if ansupvote:
                        if ansVotedUser.voting_value == 1:
                            messages.add_message(request, messages.ERROR, 'You have already upvoted this answer.')
                        elif ansVotedUser.voting_value == -1:
                            ansVotedUser.voting_value = 1
                            ansVotedUser.save()
                            messages.add_message(request, messages.SUCCESS, 'You upvoted this answer.')
                    elif ansdownvote:
                        if ansVotedUser.voting_value == 1:
                            ansVotedUser.voting_value = -1
                            ansVotedUser.save()
                            messages.add_message(request, messages.SUCCESS, 'You downvoted this answer.')
                        elif ansVotedUser.voting_value == -1:
                            messages.add_message(request, messages.ERROR, 'You have already downvoted this answer.')
            except:
                try:
                    queVotedUser = QuestionVotedUser.objects.get(
                                Q(question=question),
                                Q(voting_user=user),
                                Q(voting_value=1) | Q(voting_value=-1))

                except:
                    if request.GET['queupvote']:
                        QuestionVotedUser.objects.create(question=question, voting_user=user, voting_value=1)
                        messages.add_message(request, messages.SUCCESS, 'You upvoted this question.')
                    elif request.GET['quedownvote']:
                        QuestionVotedUser.objects.create(question=question, voting_user=user, voting_value=-1)
                        messages.add_message(request, messages.SUCCESS, 'You downvoted this question.')
                else:
                    if queupvote:
                        if queVotedUser.voting_value == 1:
                            messages.add_message(request, messages.ERROR, 'You have already upvoted this question.')
                        elif queVotedUser.voting_value == -1:
                            queVotedUser.voting_value = 1
                            queVotedUser.save()
                            messages.add_message(request, messages.SUCCESS, 'You upvoted this question.')
                    elif quedownvote:
                        if queVotedUser.voting_value == 1:
                            queVotedUser.voting_value = -1
                            queVotedUser.save()
                            messages.add_message(request, messages.SUCCESS, 'You downvoted this question.')
                        elif queVotedUser.voting_value == -1:
                            messages.add_message(request, messages.ERROR, 'You have already downvoted this question.')
        else:
            messages.add_message(request, messages.ERROR, 'You should be logged in to upvote or downvote.')


    if question:
        context = {
            'question': question,
            'answer': answer,
            'errors': None,
            'user': user
        }
        return render(request, 'questions/question_card.html', context=context)
    return render(request, 'questions/question_card.html', {'errors': 'No such question exists.'})


def get_all_users(request):
    user_list = User.objects.all()
    context = {
        'users': user_list
    }
    return render(request, 'questions/all_users.html', context=context)


@login_required
def userFeed(request):
    user = request.user
#     Find all the people this user follow and fetch the answers of these people and populate the feed
    following_qs = user.following.all()
    # This question card will contain question and its answer object
    question_card = []
    for obj in following_qs:
        person = obj.following_user_id
        for answer in person.answer_set.all():
            question_card.append({
                'question': answer.question,
                'answer': answer
            })
    context = {
        'question_card': question_card,
        'user_name': request.user.get_full_name
    }
    return render(request, 'questions/userfeed.html', context=context)

questions/templates/questions/all_users.html
{% extends 'questions/user_base.html' %}
{% block title %}
    QuoraClone | All users
{% endblock title %}

{% block content %}
    <div class="container">
    {% for user in users %}
        <p><a href="{% url 'accounts:profile' user.username %}">{{ user.get_full_name }}</a></p>
    {% endfor %}
    </div>
{% endblock content %}

questions/templates/questions/profile_answers_list.html
{% extends 'questions/user_base.html' %}

{% block title %}
    {{ profile_username }} | All answers

{% endblock title %}

{% block content %}
    <div class="container">
    {% if profile_answers_list %}
        {% for answer in profile_answers_list %}
            <div class="card" style="padding-bottom: 20px; padding-left: 20px; margin-bottom: 30px">
            <div class="row">
                <div class="col-sm-8">
            <div>
                Answer - {{ answer.answer_text }}
            </div>
                    <div>
                Answered By - <a href="{% url 'accounts:profile' answer.answerer.username %}">{{ answer.answerer.get_full_name }}</a>
            </div>
                    </div>
                <div class="col-sm-4">
            <button type="button" class="btn btn-dark btn-sm" data-toggle="modal" data-target="#answerDetailModal{{ forloop.counter }}">
                      Show Answer Details
            </button>
                    </div>
            </div>
            </div>
                <div class="modal fade" id="answerDetailModal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" id="{{ forloop.counter }}" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">

                      <div>Answered On - {{ answer.timestamp }}</div>
                      <div>Last Updated - {{ answer.updated }}</div>

                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
        {% endfor %}
    {% else %}
        Currently {{ request.user.get_full_name }} has not answered any questions.
    {% endif %}
    </div>
{% endblock content %}

questions/templates/questions/profile_questions_list.html
{% extends 'questions/user_base.html' %}

{% block title %}
    {{ profile_username }} | All questions
{% endblock title %}

{% block content %}
    <div class="container">
    {% if questions_list %}
        {% for question in questions_list %}
            <div class="card" style="padding-bottom: 20px; padding-left: 20px; margin-bottom: 30px">
            <div class="row">
                <div class="col-sm-8">
            <div>
                Question Title - {{ question.question_title }}
            </div>
            <div>
                Question Description - {{ question.question_description }}
            </div>
                    <div>
                Asked By - <a href="{% url 'accounts:profile' question.question_asker.username %}">{{ question.question_asker.get_full_name }}</a>
            </div>
                    </div>
                <div class="col-sm-4">
            <button type="button" class="btn btn-dark btn-sm" data-toggle="modal" data-target="#questionDetailModal{{ forloop.counter }}">
                      Show Question Details
            </button>
                    </div>
            </div>
            </div>
        <div class="modal fade" id="questionDetailModal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" id="{{ forloop.counter }}" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">

              <div>Asked On - {{ question.timestamp }}</div>
              <div>Last Updated - {{ question.updated }}</div>

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    {% else %}
        Currently {{ profile_username }} has not asked any questions.
    {% endif %}
    </div>
{% endblock content %}

questions/templates/questions/question_card.html
{% extends 'questions/user_base.html' %}
{% block title %}
    {% load custom_filters %}
    {% if errors %}
    {{ errors }}
    {% else %}
            {{ ques.question_title }}
    {% endif %}
{% endblock title %}

{% block content %}
    <a class="btn btn-primary bg-info btn-lg" href="{% url 'questions:feed' %}" role="button">Back to Feed</a>
<div class="container" >

    <div class="card" style="padding-bottom: 20px; padding-left: 20px; margin-bottom: 30px">
            <div class="row">
                <div class="col-sm-8">
            <div>
                Question Title - {{ question.question_title }}
            </div>
            <div>
                Question Description - {{ question.question_description }}
            </div>
                    <div>
                Asked By - <a href="{% url 'accounts:profile' question.question_asker.username %}">{{ question.question_asker.get_full_name }}</a>
            </div>
                    </div>
                <div class="col-sm-4">
            <button type="button" class="btn btn-dark btn-sm" data-toggle="modal" data-target="#questionDetailModal">
                      Show Question Details
            </button>
                    </div>
            </div>


        <div class="row">
            <form action="" method="GET">
            <button value="1" type="submit" name="queupvote" class="btn btn-light">Upvote Question</button>
                </form>
            <form action="." method="GET">
            <button type="submit" value="-1" name="quedownvote" class="btn btn-light">Downvote Question</button>
                </form>
        {% if not request.GET.ans_number %}
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        {% endif %}
        </div>

<div class="row">
            <button type="button" class="btn btn-light btn-sm" data-toggle="modal" data-target="#questionUpvoterModal">
                      View Question Upvoters
            </button>
            <button type="button" class="btn btn-light btn-sm" data-toggle="modal" data-target="#questionDownvoterModal">
                      View Question Downvoters
            </button>

            <div class="modal fade" id="questionUpvoterModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog"  role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    {% for queupvoter in question.get_question_upvoters %}
                        <p><a href="{% url 'accounts:profile' queupvoter.username %}">{{ queupvoter.get_full_name }}</a></p>
                      {% endfor %}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>


            <div class="modal fade" id="questionDownvoterModal{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" id="{{forloop.counter}}" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    {% for quedownvoter in question.get_question_downvoters %}
                        <p><a href="{% url 'accounts:profile' quedownvoter.username %}">{{ quedownvoter.get_full_name }}</a></p>
                      {% endfor %}

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

{% for ans in answer %}
<div class="container">
        <div class="card" style="padding: 20px; margin-bottom: 20px">
            <div class="row" style="padding-top: 20px">
                <div class="col-sm-8">
                <div>
                    Answered by - <a href="{% url 'accounts:profile' ans.answerer.username %}">{{ ans.answerer.get_full_name }}</a>
                </div>
                <div>
                    {{ ans.answer_text }}
                </div>
                </div>
                <div class="col-sm-4">
            <button type="button" class="btn btn-dark btn-sm" data-toggle="modal" data-target="#answerDetailModal{{ans.answerer.id}}">
                      Show Answer Details
            </button>
                    </div>
            </div>

            <div class="row">
            <button type="button" class="btn btn-light btn-sm" data-toggle="modal" data-target="#answerUpvoterViewModal{{ forloop.counter }}">
                      View Answer Upvoters
            </button>
            <button type="button" class="btn btn-light btn-sm" data-toggle="modal" data-target="#answerDownvoterViewModal{{ forloop.counter }}">
                      View Answer Downvoters
            </button>
            </div>

            <div class="row">
            <form action="" method="GET">
                <input name="ans_number" type="hidden" value="{{ forloop.counter }}">
            <button value="1" type="submit" name="ansupvote" class="btn btn-light">Upvote Answer</button>
                </form>
            <form action="." method="GET">
                <input name="ans_number" type="hidden" value="{{ forloop.counter }}">
            <button type="submit" value="-1" name="ansdownvote" class="btn btn-light">Downvote Answer</button>
                </form>

            {% if request.GET.ans_number|changeToInt == forloop.counter %}
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            {% endif %}

        </div>

            <div class="modal fade" id="answerUpvoterViewModal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" id="{{forloop.counter}}" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    {% for ansupvoter in ans.get_answer_upvoters %}
                        <p><a href="{% url 'accounts:profile' ansupvoter.username %}">{{ ansupvoter.get_full_name }}</a></p>
                      {% endfor %}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>

            <div class="modal fade" id="answerDownvoterViewModal{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" id="{{forloop.counter}}" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    {% for ansdownvoter in ans.get_answer_downvoters %}
                        <p><a href="{% url 'accounts:profile' ansdownvoter.username %}">{{ ansdownvoter.get_full_name }}</a></p>
                      {% endfor %}

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>

        </div>

    </div>
    <div class="modal fade" id="answerDetailModal{{ans.answerer.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" id="{{ans.answerer.id}}" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <div>Answered On - {{ ans.timestamp }}</div>
          <div><a href="{% url 'accounts:profile' ans.answerer.username %}">{{ ans.answerer.get_full_name }}</a></div>
      <div>Last Updated - {{ ans.updated }}</div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endfor %}


    <div class="modal fade" id="questionDetailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      <div>Asked On - {{ question.timestamp }}</div>
      <div>Last Updated - {{ question.updated }}</div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

questions/templates/questions/user_base.html
<!DOCTYPE html>
<html>
<head>

	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="">
	<title>{% block title %}QuoraClone{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
{% block content %}
{% endblock content %}

{% block libraries %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
{% endblock libraries %}
</body>
</html>

questions/templates/questions/userfeed.html
{% extends 'questions/user_base.html' %}
{% block title %}
Feed | {{ user_name }}
{% endblock title %}

{% block content %}
    {% if question_card %}
        <div class="container">
        {% for question_info in question_card %}
        <div style="align-content:center; width:60rem" class="card text-center ml-auto">
          <div class="card-header">
              {{ question_info.question.question_title }}
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ question_info.question.question_description }}</h5>
            <p class="card-text">{{ question_info.answer.answer_text|truncatechars:20 }}</p>
            <a href="{% url 'questions:question_card' question_info.question.question_title %}" class="btn btn-primary">Check Full Question</a>
          </div>
        </div>
        {% endfor %}
    </div>

    {% else %}

    <div class="modal fade" id="ask-user-to-follow-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Follow Some People</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Your feed is currently empty.
          </div>
            <div class="modal-body">
            Follow some people to improve your feed.
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <a href="{% url 'questions:get_all_users' %}"><button type="button" class="btn btn-primary">Follow</button></a>
          </div>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

    <script>
    $(document).ready(function(){
        $("#ask-user-to-follow-modal").modal('show');
    });
    </script>
    {% endif %}
{% endblock content %}