QuoraClone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='base.html')),
    path('main/', include('questions.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
]

accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/<str:username>/', views.userProfile, name='profile'),
    path('register/', views.registerUser, name='register'),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('change-password/', views.changePassword, name='changePassword'),

]

questions/urls.py
from django.urls import path, include
from . import views

app_name = 'questions'
urlpatterns = [
    path('home/', views.userFeed, name='feed'),
    path('all-users/', views.get_all_users, name='get_all_users'),
    path('home/ques/<str:question_title>/', views.get_question, name='question_card'),
    path('<str:username>/all_questions/', views.get_profile_questions, name='user_questions'),
    path('<str:username>/all_answers/', views.get_profile_answers, name='user_answers'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Welcome to QuoraClone</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
        body, html {
          height: 100%;
       }

    .bg {
      /* The image used */
      background-image: url("https://images.unsplash.com/photo-1445112098124-3e76dd67983c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1047&q=80");

      /* Full height */
      height: 100%;

      /* Center and scale the image nicely */
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
    }
    </style>
</head>
<body>
<div class="bg">
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4" style="color: red">Quora</h1>
            <p class="lead">A place to share knowledge and better understand the world.</p>
            <hr class="my-4">
            {% if user.is_authenticated %}
                <a class="btn btn-primary btn-lg" href="{% url 'questions:feed' %} " role="button">View Feed</a>
                <a class="btn btn-primary btn-lg" href="{% url 'accounts:logout' %} " role="button">Logout</a>
            {% else  %}
                <a class="btn btn-primary btn-lg" href="{% url 'accounts:login' %} " role="button">Login</a>
                <a class="btn btn-primary btn-lg" href="{% url 'accounts:register' %}" role="button">Signup</a>
            {% endif %}
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>